apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-svc"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
